# Default values for mirrorbits.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jenkinsciinfra/mirrorbits
  tag: 0.1.97
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
service:
  type: ClusterIP
  port: 80
  files:
    type: ClusterIP
    port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/tls-acme: "true"
  hosts: []
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         serviceNameSuffix: files
  #       - path: /.*[.](deb|hpi|war|rpm|msi|pkg|sha256|md5sum|zip|gz|pdf|json|svg|sh|jpeg|ico|png|html)$
  #         pathType: ImplementationSpecific
  #   - host: fallback.chart-example.local
  #     paths:
  #       - path: /
  #         serviceNameSuffix: files
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
geoipupdate:
  image:
    repository: maxmindinc/geoipupdate
    tag: v6.0.0
  # Secret values, set to empty below for reference:
  account_id: ""
  license_key: ""
  editions: GeoLite2-ASN GeoLite2-City GeoLite2-Country
  update_frequency: 24
logs:
  volume:
    emptyDir: {}
    ## Volume contains the Pod Volume definition. Example with an existing PVC:
    # persistentVolumeClaim:
    #   claimName: <PVC name>
# mirrorbits.conf data, to be completed as secret with Redis credentials
conf: |
  Repository: /srv/repo
  Templates: /usr/share/mirrorbits/templates
  RedisAddress: mirrors-redis-master:6379
repository:
  name: mirrorbits-lite-binary
  persistentVolumeClaim:
    enabled: false
    # spec hold persistentVolumeClaim spec
    spec: {}
  persistentVolume:
    enabled: false
    # spec hold persistentVolume spec
    spec: {}
  secrets:
    enabled: false
    # data hold secrets data used by persistentVolume
    data: {}

poddisruptionbudget:
  minAvailable: 1
