apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-health-scoring.fullname" . }}
  labels:
{{ include "plugin-health-scoring.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plugin-health-scoring.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plugin-health-scoring.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "plugin-health-scoring.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          liveness:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: UPDATE_CENTER_CRON
              value: {{ .Values.config.ucCron | squote }}
            - name: PROBE_ENGINE_CRON
              value: {{ .Values.config.peCron | squote }}
            - name: POSTGRES_HOST
              value: {{ .Values.database.server | squote }}
            - name: POSTGRES_PORT
              value: {{ .Values.database.port | squote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name | squote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user | squote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | squote }}
            - name: GITHUB_OAUTH
              value: {{ .Values.config.githubOauth | squote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
