{{- if .Values.jenkinsioEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "jenkinsio.fullname" .}}
  labels: {{include "jenkinsio.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{include "jenkinsio.name" .}}
      app.kubernetes.io/instance: {{.Release.Name}}
  template:
    metadata:
      labels: {{include "jenkinsio.labels" . | nindent 8}}
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/configmap.yaml") . | sha256sum}}
    spec:
      automountServiceAccountToken: false
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.en.repository }}:{{ .Values.images.en.tag }}"
          imagePullPolicy: {{ .Values.images.en.pullPolicy }}
          ports:
              - name: {{ include "jenkinsio.fullname" . }}
                containerPort: 80
                protocol: TCP
          livenessProbe:
              httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/conf.d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.jenkinsio }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: html
{{- if .Values.htmlVolume -}}
{{- toYaml .Values.htmlVolume | nindent 10 }}
{{- else }}
          emptyDir: {}
{{- end }}
        - name: config
          configMap:
            name: {{ include "jenkinsio.fullname" . }}
{{- end }}
