apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkinsio.fullname" . }}-zh
  labels: {{ include "zh-jenkinsio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{include "jenkinsio.name" .}}-zh
      app.kubernetes.io/instance: {{.Release.Name}}-zh
  template:
    metadata:
      labels: {{include "zh-jenkinsio.labels" . | nindent 8}}
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/zh-configmap.yaml") . | sha256sum}}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.zh.repository }}:{{ .Values.images.zh.tag }}"
          imagePullPolicy: {{ .Values.images.zh.pullPolicy }}
          ports:
              - name: {{ include "jenkinsio.fullname" . }}-zh
                containerPort: 80
                protocol: TCP
          livenessProbe:
              httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/zh
            - name: config
              mountPath: /etc/nginx/conf.d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with index .Values.affinity "jenkinsio-zh" }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: html
{{- if .Values.zhHtmlVolume -}}
{{- toYaml .Values.zhHtmlVolume | nindent 10 }}
{{- else }}
          emptyDir: {}
{{- end }}
        - name: config
          configMap:
            name: {{ include "jenkinsio.fullname" . }}
