{{- if .Values.zhJenkinsioEnabled }}
{{ if .Values.zhAzureStorageAccountName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkinsio.fullname" . }}-zh
type: Opaque
data:
  azurestorageaccountname: {{ .Values.zhAzureStorageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.zhAzureStorageAccountKey | b64enc }}
{{- end }}
{{- end }}
