---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ircbot.fullname" . }}
  labels: {{ include "ircbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  github: |
   login={{ .Values.github.username }}
   password={{ .Values.github.password }}

  jira: |
    userName={{ .Values.jira.username }}
    password={{ .Values.jira.password }}

  nick_password: {{ .Values.ircNickPassword }}
