{{ if .Values.persistence.persistentVolume.enabled -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.name | default (printf "%s-binary" (include "rsyncd.fullname" .)) }}
  labels:
    data: {{ .Values.persistence.name | default (printf "%s-binary" (include "rsyncd.fullname" . )) }}
spec:
{{ toYaml .Values.persistence.persistentVolume.spec | nindent 2 }}
{{- end -}}
