apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyncd.fullname" . }}
  labels:
{{ include "rsyncd.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.LoadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  loadBalancerSourceRanges:
    {{- range .Values.service.whitelisted_sources }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: rsyncd
  selector:
    app.kubernetes.io/name: {{ include "rsyncd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
