{{ if $.Values.persistent.secret.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.persistent.volumeClaim.name | default (printf "%s-binary" (include "rsyncd-mirror.fullname" .))  }}
type: Opaque
data:
  {{- range $key, $val := .Values.persistent.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end -}}
