apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyncd-mirror.fullname" . }}-rsyncd
  labels:
{{ include "rsyncd-mirror.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.rsyncd.type }}
  {{- if eq .Values.service.rsyncd.type "LoadBalancer" }}
  {{- if .Values.service.rsyncd.IP }}
  loadBalancerIP: {{ .Values.service.rsyncd.IP }}
  {{- end }}
  loadBalancerSourceRanges:
    {{- range .Values.service.rsyncd.whitelisted_sources }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}

  ports:
    - port: {{ .Values.service.rsyncd.port }}
      targetPort: 873
      protocol: TCP
      name: rsyncd
  selector:
    app.kubernetes.io/name: {{ include "rsyncd-mirror.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
