{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mirrorbits-lite.serviceAccountName" . }}
  labels:
{{ include "mirrorbits-lite.labels" . | indent 4 }}
{{- end -}}
