apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirrorbits-lite.fullname" . }}
  labels:
{{ include "mirrorbits-lite.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mirrorbits-lite.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
