{{ if $.Values.persistent.volume.enabled -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.persistent.volume.name | default (printf "%s-binary" (include "mirror.fullname" .))}}
  labels:
    data: {{ $.Values.persistent.volume.name | default (printf "%s-binary" (include "mirror.fullname" .))}}
spec:
{{ toYaml $.Values.persistent.volume.spec | nindent 2 }}
{{- end -}}
