apiVersion: v1
appVersion: "1.0"
description: A Helm chart for javadoc.jenkins.io
name: javadoc
version: 0.5.2
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: Jenkins Infra Team
  url: https://www.jenkins.io/projects/infrastructure/
sources:
- https://github.com/jenkins-infra/helm-charts
