{{- if .Values.serviceAccountRestarter -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mirrorbits.fullname" . }}-restarter
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-restarter
  annotations:
    kubernetes.io/service-account.name: {{ include "mirrorbits.fullname" . }}-restarter
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mirrorbits.fullname" . }}-restarter
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
rules:
  - apiGroups: ["apps"]
    # No permission are required on pod or replicaset for the "rollout restart/status" commands
    resources: ["deployments"]
    # Restrict to only the mirrorbits deployment, forbidden for others in this namespace.
    resourceNames: ["{{ include "mirrorbits.fullname" . }}"]
    # get and patch enable "rollout restart" while watch and list enables "rollout status --watch"
    verbs: ["get","patch","watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mirrorbits.fullname" . }}-restarter
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "mirrorbits.fullname" . }}-restarter
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name:  {{ include "mirrorbits.fullname" . }}-restarter
  apiGroup: rbac.authorization.k8s.io
---
{{- end -}}
