apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirrorbits.fullname" . }}-files
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.files.type }}
  ports:
    - port: {{ .Values.service.files.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mirrorbits.name" . }}-files
    app.kubernetes.io/instance: {{ .Release.Name }}-files
