---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
{{ include "geoipupdate.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.geoipupdate.cron }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
              {{ toYaml . | nindent 16 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "geoipupdate.fullname" . }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: geoipupdate
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tmpdir
                  mountPath: /tmp
                  readOnly: false
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- with .Values.geoipupdate.dryrun }}
                - name: GEOIPUPDATE_DRYRUN
                  value: {{ . | quote }}
                {{- end }}
                {{- with .Values.geoipupdate.editions }}
                - name: GEOIPUPDATE_EDITION_IDS
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_name }}
                - name: STORAGE_NAME
                  value: {{ . }}
                {{- end }}
                {{- with .Values.geoipupdate.storage_fileshare }}
                - name: STORAGE_FILESHARE
                  value: {{ . }}
                {{- end }}
                {{- if .Values.geoipupdate.rolloutrestart }}
                {{- if .Values.geoipupdate.rolloutrestart.enable }}
                - name: GEOIPUPDATE_ROLLOUT
                  value: {{ include "geoipupdate.rollout" . }}
                {{- end }}
                {{- end }}
              envFrom:
              - secretRef:
                  name: {{ include "geoipupdate.fullname" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: tmpdir
              emptyDir:
                medium: "Memory"
