apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpd.fullname" . }}
  labels:
{{ include "httpd.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.files.type }}
  ports:
    - port: {{ .Values.service.files.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "httpd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
