# Default values for accounts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jenkinsciinfra/account-app
  tag: 0.5.16
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 8080
# Please define ingress settings into environment variable
ingress:
  enabled: true
  className: ""
#  annotations:
#    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: accounts.jenkins.io
#      paths:
#        - path: /
#
#  tls:
#    - secretName: accounts-tls
#      hosts:
#        - accounts.jenkins.io
# We usually recommend not to specify default resources and to leave this as a conscious: null # choice for the user. This also increases chances charts run on environments with little
resources: {}
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
ldap:
  url: ldaps://ldap.jenkins.io:636/
  managerDn: cn=admin,dc=jenkins-ci,dc=org
  newUserBaseDn: ou=people,dc=jenkins-ci,dc=org
  password: ""
jira:
  username: accountapp
  password: ""
  url: https://issues.jenkins.io/
seats: 2
seniority: 12
smtp:
  auth: true
  server: smtp.sendgrid.net
  sender: admin@jenkins-ci.org
  port: 587
  user: null
  password: ""
appUrl: https://accounts.jenkins.io
election:
  open: 1970-01-01
  close: 1970-01-02
  logDir: /var/log/accountapp/elections
  candidates: bob,alice
poddisruptionbudget:
  minAvailable: 1
