apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rsyncd.fullname" . }}-rsyncd-conf
data:
  rsyncd.conf: |
    # /etc/rsyncd: configuration file for
    rsync daemon mode

    # See rsyncd.conf man page for more options.

    # configuration example:

    uid = {{ .Values.configuration.uid }}
    gid = {{ .Values.configuration.gid }}
    use chroot = yes
    max connections = 0
    pid file = /var/run/rsyncd.pid
    exclude = lost+found/
    transfer logging = yes
    log file = /dev/stdout
    ignore nonreadable = yes
    dont compress   = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2
    port = {{ .Values.configuration.port }}
    # motd file = {{ .Values.configuration.motd_path }}
    max verbosity = 4

    # Timeout in seconds
    timeout = 300

    # Any attempted uploads will fail
    read only = true

    # Downloads will be possible if file permissions on the daemon side allow them
    write only = false

    hosts allow = {{ .Values.configuration.hosts_allow }}

    [jenkins]
    path = {{ .Values.configuration.datadir }}
    comment = {{ .Values.configuration.comment }}
