{{ if $.Values.repository.secrets.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpd.fullname" . }}-binary
type: Opaque
data:
  {{- range $key, $val := .Values.repository.secrets.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end -}}
