{{- if .Values.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-caching-proxy.fullname" . }}-basic-auth
  labels:
{{ include "artifact-caching-proxy.labels" . | indent 4 }}
type: Opaque
data:
  auth: {{ .Values.auth.basicAuth | b64enc }}
{{- end }}
