apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss2twitter.fullname" . }}
  labels:
    {{- include "rss2twitter.labels" . | nindent 4 }}
type: Opaque
data:
  TWI_CONSUMER_KEY: {{ .Values.twitter.consumerKey | b64enc }}
  TWI_CONSUMER_SECRET: {{ .Values.twitter.consumerSecret | b64enc }}
  TWI_ACCESS_TOKEN: {{ .Values.twitter.accessToken | b64enc }}
  TWI_ACCESS_SECRET: {{ .Values.twitter.accessSecret | b64enc }}
