{{- if .Values.global.storage.enabled }}
  {{- if .Values.global.storage.persistentVolume }}
    {{ with .Values.global.storage.persistentVolume.azureFile -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits-parent.pv-secretname" $ }}
  labels:
{{ include "mirrorbits-parents.labels" $ | nindent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .storageAccountKey | b64enc }}
    {{- end -}}
  {{- end -}}
{{- else -}}
  {{- if .Values.global.storageMirrorbits.enabled }}
    {{- if .Values.global.storageMirrorbits.persistentVolume }}
      {{ with .Values.global.storageMirrorbits.persistentVolume.azureFile -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits-parent.pv-secretname" $ }}-mirrorbits
  labels:
{{ include "mirrorbits-parents.labels" $ | nindent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .storageAccountKey | b64enc }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- if .Values.global.storageHttpd.enabled }}
    {{- if .Values.global.storageHttpd.persistentVolume }}
      {{ with .Values.global.storageHttpd.persistentVolume.azureFile -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits-parent.pv-secretname" $ }}-httpd
  labels:
{{ include "mirrorbits-parents.labels" $ | nindent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .storageAccountKey | b64enc }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
